### ISSUE TITLE
missing synchronator.conf

### ISSUE THREAD

**Issue by mwgrient** [therealmuffin/synchronator#12]
Hi,
I have fiddled with alsa on my Simple Audio Roomplayer+ (SAR+), while I should not have done this? (changing volume > alsamixer true ssh)

Now there is a empty synchronator.conf file. While it should be populated? 

My question is, do you have  config file of synchronator for the SAR+ ?

**Comment by therealmuffin** [comment]
This isn't really the place for support with the Reloaded upgrade. If the below doesn't answer your question, please contact me via email (though if you'd like help with configuring Synchronator to work with your amplifier, you can reopen this issue).

Synchronator is included in the upgrade but it's inactivated (with a sample configuration included). If your amplifier can be controlled via the network and you'd like to configure Synchronator, you can. That way, you can control your amplifier sound volume directly from your Roomplayer. In short, you can leave Synchronator deactivated and the configuration file empty.
