### ISSUE TITLE
Sending ASCII

### ISSUE THREAD

**Issue by Fheodoor** [therealmuffin/synchronator#13]
Hello,

Trying to connect trough TCP to a Lyngdorf Amplifier (Serial is working perfect, even when I use TCP2Serial), but on the newer ones it seems the command (tail) is not terminating. When I do in bash for example : echo -e '!VOL(-999)\0D' > /dev/tcp/ip/port it’s working flawlessly. 0D is <CR>, so should be \r , but for one or the other reason it’s not working. Can I try an ASCII code? Any suggestions?

Thanks!

**Comment by therealmuffin** [comment]
Hello Fheodoor,

Couple of questions:
1) What exactly do you mean with 'the newer ones'?
2) Which Lyngdorf amp are you trying to control?
3) Can you share the config you're currently using (and which is working for serial)?

Kind Regards, Maarten

**Comment by therealmuffin** [comment]
I'm assuming your issue has been resolved. Please reopen this issue if that's not the case.
