### ISSUE TITLE
volume levels remapped with mpd 0.20.x

### ISSUE THREAD

**Issue by Schorsch99** [therealmuffin/synchronator#6]
Starting with mpd 0.20.x volume levels are "remapped".
It appears as if the curve sent is logarithmic:
Controlpoint > Receiver
0 > 0
5 > 11
10 > 21
20 > 37
...
86 > 91
97 > 97
100 > 99
Everything works fine with mpd 0.19.1

**Comment by therealmuffin** [comment]
Thanks for posting this issue!

I've committed a patch which should fix this issue. I've added an option to normalize Alsa volume. To activate this feature you can add the following option to the configuration file:
mixer_normalize=TRUE;

I'll close this issue. If this doesn't work or not as expected, please reopen this issue.
