### ISSUE TITLE
feature request: softer volume change

### ISSUE THREAD

**Issue by Schorsch99** [therealmuffin/synchronator#7]
feature request: when changing volume, ramp up or down quickly from "old" to "new" level rather than instantly switching from one value to the next.

**Comment by therealmuffin** [comment]
I see your point (I think). However, to know what the 'new' target volume is necessarily causes a delayed response which I don't like.

However, currently, when mimicking absolute volume control with amplifiers only having relative volume control (plus/min), I've implemented the following approach: the target volume level is continuously updated as you change the volume (target volume level as in latest volume level received from computer end) and the actual volume level at the amplifier end moves in configurable timed steps towards that target (and changes direction -up/down- as required). That prevents some amplifiers getting an overload of commands and enables a more smooth volume control.

I've been thinking about implementing that also for absolute volume control (as you are using). Would that be something that could work for you?

**Comment by Schorsch99** [comment]
That would be a very nice feature and pretty much what I had in mind, provided that these "ballistics" also work for larger volume steps.
Because -if my observations are correct- BubbleUPNP for example does not send continuous volume updates as you move the control. I think it only sends one update on release.
But then again that assumption may be wrong, as it is based purely on observation, not on tcp tracing or debug logs.

Am 2. Mai 2017 22:10:41 MESZ schrieb Muffinman <notifications@github.com>:

**Comment by therealmuffin** [comment]
Ok, put the feature on my todo list. Will report when there is news, no time frame though.

**Comment by therealmuffin** [comment]
I've setup the basic implementation of this idea. For linear configuration (such as yours) this should work quite well (though it still requires a bit of testing). For amplifiers with logarithmic volume curves I still need to do some work.

You can activate this functionality by downloading/compiling the smoothvolume branch. In the config you can set in the volume section the option: 
timeout=100;

If still interested, let me know how it works so far.

**Comment by therealmuffin** [comment]
Merged smoothvolume branch with master
